- plugins/extractors/csv/extractor.go
- plugins/extractors/csv/extractor_test.go
- plugins/extractors/populate.go
- extract column names from a single or a directory of csv files.
> feat: CSV extractor

- cmd/run.go
- main.go
- plugins/extractors/bigquery/extractor.go
- plugins/extractors/bigtable/extractor.go
- plugins/extractors/bigtable/extractor_test.go
- plugins/extractors/clickhouse/extractor.go
- plugins/extractors/csv/extractor.go
- plugins/extractors/csv/extractor_test.go
- plugins/extractors/date/date.go
- plugins/extractors/elastic/extractor.go
- plugins/extractors/gcs/extractor.go
- plugins/extractors/gcs/extractor_test.go
- plugins/extractors/github/extractor.go
- plugins/extractors/grafana/extractor.go
- plugins/extractors/grafana/extractor_test.go
- plugins/extractors/kafka/extractor.go
- plugins/extractors/kafka/extractor_test.go
- plugins/extractors/metabase/extractor.go
- plugins/extractors/metabase/extractor_test.go
- plugins/extractors/mongodb/extractor.go
- plugins/extractors/mongodb/extractor_test.go
- plugins/extractors/mssql/extractor.go
- plugins/extractors/mssql/extractor_test.go
- plugins/extractors/mysql/extractor.go
- plugins/extractors/mysql/extractor_test.go
- plugins/extractors/postgres/postgres.go
- plugins/logger.go
- plugins/sinks/console/sink.go
- plugins/testutils/logger.go
- update plugins log to use odpf/salt logger
- fix infinite loop on bigquery extractor if access is authorized
- log recipe details on debug log level
> refactor(log): switch to odpf/salt logger

- cmd/lint.go
- cmd/list.go
- cmd/root.go
- go.mod
- go.sum
- registry/registry.go
Add list command for printing a list of extractors, sinks and processors.
> feat: add list plugin command

- cmd/gen.go
- cmd/help.go
- cmd/lint.go
- cmd/list.go
- cmd/root.go
- cmd/run.go
- go.mod
- go.sum
- main.go
Add custom help message with command grouping capability. (Inspired from Github cli.)
> feat: add custom help

- plugins/extractors/bigquery/bigquery.go
- Add partition field to bigquery metadata
> feat(bigquery): add partition field to metadata

- plugins/extractors/bigquery/bigquery.go
- extract 30 rows from bigquery as a preview
> feat(bigquery): extract preview

- cmd/lint.go
- cmd/list.go
- cmd/root.go
- Add lint command for recipes
> feat: add lint command

- .goreleaser.yml
- Makefile
- README.md
- cmd/root.go
- cmd/version.go
- go.mod
- go.sum
- main.go
Version command returns the current version of the client.
> feat: add version command

- .github/workflows/build_dev.yml
- .goreleaser.yml
- setup dev workflow to push `meteor:dev` image on any branch manually using `workflow_dispatch`
this is to allow feature branch to be tested before merging it default(main) branch.
> chore: create dev workflow to test feature branch

- agent/agent.go
- agent/run.go
- cmd/run.go
Creates the run report in tabular form
> feat: generate tabular run report

- docs/reference/extractors.md
- go.mod
- go.sum
- plugins/extractors/cassandra/README.md
- plugins/extractors/cassandra/cassandra.go
- plugins/extractors/cassandra/cassandra_test.go
- plugins/extractors/cassandra/localConfig/cassandra.yaml
- plugins/extractors/populate.go
| Field | Sample Value |
| :---- | :---- |
| `resource.urn` | `my_keyspace.my_table` |
| `resource.name` | `my_table` |
| `resource.service` | `cassandra` |
| `description` | `table description` |
| `profile.total_rows` | `rows` |
| `schema` | [][Column](#column) |
| Field | Sample Value |
| :---- | :---- |
| `name` | `column_name` |
| `datatype` | `type` |
> feat: add cassandra extractor

- agent/agent.go
- agent/agent_test.go
- agent/config.go
- agent/retrier.go
- agent/retry.go
- cmd/lint.go
- cmd/root.go
- cmd/run.go
- config/config.go
- go.mod
- main.go
- plugins/errors.go
- plugins/sinks/columbus/sink.go
- plugins/sinks/columbus/sink_test.go
> feat(agent): add retry mechanism

- agent/agent.go
- agent/agent_test.go
Fixes for the issue: https://github.com/odpf/meteor/issues/256
> fix: unrecorded metrics on failed plugin initialization

- plugins/extractors/bigquery/bigquery.go
- plugins/extractors/bigtable/bigtable.go
- plugins/extractors/cassandra/cassandra.go
- plugins/extractors/clickhouse/README.md
- plugins/extractors/clickhouse/clickhouse.go
- plugins/extractors/clickhouse/clickhouse_test.go
- plugins/extractors/couchdb/README.md
- plugins/extractors/couchdb/couchdb.go
- plugins/extractors/couchdb/couchdb_test.go
- plugins/extractors/csv/csv.go
- plugins/extractors/gcs/gcs.go
- plugins/extractors/github/github.go
- plugins/extractors/grafana/grafana.go
- plugins/extractors/kafka/kafka.go
- plugins/extractors/metabase/metabase.go
- plugins/extractors/mongodb/README.md
- plugins/extractors/mongodb/mongodb.go
- plugins/extractors/mongodb/mongodb_test.go
- plugins/extractors/mssql/README.md
- plugins/extractors/mssql/mssql.go
- plugins/extractors/mssql/mssql_test.go
- plugins/extractors/mysql/README.md
- plugins/extractors/mysql/mysql.go
- plugins/extractors/mysql/mysql_test.go
- plugins/extractors/optimus/optimus.go
- plugins/extractors/postgres/README.md
- plugins/extractors/postgres/postgres.go
- plugins/extractors/postgres/postgres_test.go
- plugins/extractors/superset/superset.go
- sample-recipe.yaml
- Update the extractor config by replacing login credentials with the dynamic connection URL.
> feat: connect database with connection URL

- docs/docs/reference/extractors.md
- plugins/extractors/oracle/README.md
- plugins/extractors/oracle/oracle.go
- plugins/extractors/oracle/oracle_test.go
- plugins/extractors/populate.go
> feat: add oracle extractor

- .github/workflows/plugin_test.yml
- Makefile
- plugins/extractors/bigquery/bigquery_test.go
- plugins/extractors/csv/csv_test.go
- plugins/extractors/elastic/elastic_test.go
- plugins/extractors/gcs/gcs_test.go
- plugins/extractors/grafana/grafana_test.go
- plugins/extractors/metabase/metabase_test.go
- plugins/extractors/mongodb/mongodb_test.go
- plugins/extractors/mssql/mssql_test.go
- plugins/extractors/mysql/mysql_test.go
- plugins/extractors/optimus/optimus_test.go
- plugins/extractors/postgres/postgres_test.go
- Created a command to run plugins test
- Created a GitHub workflow to run plugins test only on main branch
> feat: add command to test plugins file

- cmd/root.go
- go.mod
- go.sum
- main.go
- Add better error messages for wrong user commands. 
- Add reference command. 
- Add shell completion command
> feat: add messages for error and reference

- docs/docs/reference/extractors.md
- plugins/extractors/mariadb/README.md
- plugins/extractors/mariadb/mariadb.go
- plugins/extractors/mariadb/mariadb_test.go
- plugins/extractors/populate.go
| Field | Sample Value |
| :---- | :---- |
| `urn` | `my_database.my_table` |
| `name` | `my_table` |
| `source` | `mariadb` |
| `description` | `table description` |
| `profile.total_rows` | `2100` |
| `schema` | [][Column] |
| Field | Sample Value |
| :---- | :---- |
| `name` | `total_price` |
| `description` | `item's total price` |
| `data_type` | `decimal` |
| `is_nullable` | `true` |
| `length` | `12,2` |
> feat: add MariaDB extractor

- cmd/run.go
- go.mod
- go.sum
Adding a progress bar denoting the progress of `meteor run recipe` command.
Have used `github.com/cheggaaa/pb/` for the purpose. Let me know if yo have seen some other alternative based on plans around meteor!!
> feat: add progress bar

- cmd/run.go
- Resolved failing `golangci-lint` workflow
> fix(lint): fix linting errorcheck 

- agent/agent.go
- agent/agent_test.go
> feat: log extracted record information

- cmd/new.go
Users can enable interactive mode by setting the `interactive` (shorthand `i`) flag.
> feat: interactive mode in new cmd

- README.md
- docs/docs/guides/2_manage_recipes.md
w.r.t to changes in gen command and `$ meteor new` command by issue #301
> docs: add new command

- plugins/extractors/presto/presto_test.go
- test/utils/dockertest.go
Fixing flaky test of presto in main branch
> fix(presto): fix MaxWait and Ping query in test

- .github/workflows/plugin_test.yml
- plugins/extractors/cassandra/cassandra_test.go
- plugins/extractors/clickhouse/clickhouse_test.go
- plugins/extractors/csv/csv_test.go
- plugins/extractors/elastic/elastic_test.go
- plugins/extractors/grafana/grafana_test.go
- plugins/extractors/kafka/kafka_test.go
- plugins/extractors/metabase/testdata/expected.json
- plugins/extractors/mongodb/mongodb_test.go
- plugins/extractors/mssql/mssql_test.go
- plugins/extractors/mysql/mysql_test.go
- plugins/extractors/optimus/testdata/expected.json
- plugins/extractors/oracle/oracle_test.go
- plugins/extractors/tableau/testdata/dashboards_proto.json
- Add Plugins Test workflow for Pull Request.
- Fix all plugins test.
> fix: broken plugins test

- plugins/extractors/postgres/postgres.go
- plugins/extractors/postgres/postgres_test.go
- utils/custom_properties.go
> feat(postgres): extract table access for users

- go.mod
- go.sum
- plugins/extractors/optimus/client.go
- plugins/extractors/optimus/optimus_test.go
optimus is changing its grpc signatures.
https://github.com/odpf/optimus/tree/releases/v0.2.1/api/proto/odpf/optimus/core/v1beta1
> feat(optimus): new optimus rpc client

- plugins/extractors/tableau/README.md
- plugins/extractors/tableau/client.go
- plugins/extractors/tableau/tableau.go
- plugins/extractors/tableau/tableau_test.go
> feat: add auth_token in tableau config

- plugins/extractors/elastic/elastic.go
- plugins/extractors/elastic/elastic_test.go
> fix(elastic): fix failing tests due to unsorted indexes

- generator/recipe.go
- generator/recipe.yaml
Addresses review comment for #406
> refactor: rename template helper func {fmtSampleConfig => rawfmt}

- plugins/extractors/kafka/README.md
- plugins/extractors/kafka/kafka.go
* support TLS authentication to kafka cluster
> feat(kafka): support TLS auth in kafka extractor plugin
