odpf/meteor

- cmd/rundir.go
- plugins/sinks/console/sink.go
- plugins/sinks/kafka/sink.go
Converting kafka sink to serialize messages to proto by default instead of json
- for now this sink doesn't push kafka key, only value as the proto message
> refactor: kafka sink to serialize message as protobuf

- examples/date-kafka.yaml
- go.mod
- plugins/extractors/date/date.go
- plugins/extractors/populate.go
- plugins/sinks/kafka/sink.go
- protobuf used to create the value will be used to generate the kafka key
```
name: date-kafka-recipe
source:
type: date
sinks:
- name: kafka
config:
brokers: localhost:9092
topic: test-3
key_path: ".Action"
```
> feat: kafka sink should populate key from reflection

- docs/reference/extractors.md
- go.sum
- plugins/extractors/populate.go
- plugins/extractors/superset/README.md
- plugins/extractors/superset/superset.go
- plugins/extractors/superset/superset_test.go
- plugins/extractors/superset/typeDef.go
| Field | Sample Value |
| :---- | :---- |
| `resource.urn` | `superset.dashboard_name` |
| `resource.name` | `dashboard_name` |
| `resource.service` | `superset` |
| `resource.url` | `dashboard_url` |
| Field | Sample Value |
| :---- | :---- |
| `name` | `chart_name` |
| `dashboard_source` | `superset` |
| `description` | `chart_description` |
| `url` | `chart_url` |
| `datasource` | `chart_datasource` |
| `dashboard_urn` | `dashboard:dashboard_id` |
> feat: add superset extractor

- plugins/extractors/bigquery/README.md
- plugins/extractors/bigquery/bigquery.go
- plugins/extractors/bigquery/bigquery_test.go
- utils/config.go
- new `disable_preview` config on bigquery extractor
> feat(bigquery): make preview configurable

- generator/recipe.go
Fixes two bugs in the generator package. These bugs were caused by:
- used Sink instead of Source from template struct
- removal of mapping templateFunc for indentation.
> fix: meteor gen command

- go.mod
- go.sum
- plugins/extractors/optimus/client.go
- plugins/extractors/optimus/optimus.go
- plugins/extractors/optimus/optimus_test.go
Recently Optimus APIs have done a breaking change to version it starting from `v1beta1`. Optimus will not keep its APIs backward compatible at the moment so this is required for it to work moving forward.
> fix: upgrade optimus extractor rpc to use v1beta1 APIs

- plugins/extractors/postgres/postgres.go
While testing it for other issue, noticed that the import was missing in `postgres.go`.
Thus it kept throwing the following error on run:
`ERRO[0000] error running recipe                          duration_ms=0 err="failed to setup extractor: could not initiate extractor \"postgres\": failed to create connection: sql: unknown driver \"postgres\" (forgotten import?)" recipe=sample records_count=0`
> fix(postgres): missing import of pq driver

- go.mod
- go.sum
- plugins/extractors/oracle/README.md
- plugins/extractors/oracle/oracle.go
- plugins/extractors/oracle/oracle_test.go
The connection string is slightly different for go-ora, so fixed that and also one extra connection to DB was created, also resolved that issue. 
The oracle test is now passing.
```
PASS 
ok      github.com/odpf/meteor/plugins/extractors/oracle        347.267s
```
> fix: go-ora connection_url fix and removed redundant connection

- recipe/generator.go
- recipe/generator_test.go
- recipe/reader.go
- recipe/reader_test.go
- recipe/testdata/generator/data-1-2.yaml
- recipe/testdata/generator/data-3.yaml
- recipe/testdata/generator/expected-3.yaml
- recipe/testdata/generator/template.yaml
- recipe/testdata/testdir/test-recipe-no-name.yaml
When using the `gen` command, if `name` is not mentioned in `data`, it will fall back to the `FileName` as the recipe's name.
> feat: fallback to filename if recipe name is missing

- plugins/extractors/metabase/README.md
- plugins/extractors/metabase/metabase.go
- plugins/extractors/metabase/metabase_test.go
- plugins/extractors/metabase/testdata/expected.json
new mandatory config to label extracted metabase metadata.
```
source:
name: metabase
config:
...
instance_label: my-metabase
```
this will be used as the urn component like below
```
{
"urn": "metabase::my-metabase/dashboard/192"
}
```
> feat(metabase): use instance label for urn component

- plugins/extractors/bigquery/auditlog/auditlog.go
- plugins/extractors/bigquery/auditlog/auditlog_test.go
- plugins/extractors/bigquery/auditlog/options.go
- plugins/extractors/bigquery/bigquery.go
- plugins/extractors/bigquery/profile.go
- plugins/extractors/bigquery/profile_test.go
- add table name to filter logadmin query
- collect log per table instead of building a global hash map
> refactor(bigquery): add table name to filter logadmin query

- plugins/extractors/optimus/README.md
- plugins/extractors/optimus/client.go
- plugins/extractors/optimus/optimus.go
- plugins/extractors/optimus/optimus_test.go
new `max_size_in_mb1` in `optimus` extractor to set max megabytes for GRPC client to receive message.
```
source:
name: optimus
config:
host: optimus.com
max_size_in_mb: 100
```
> feat(optimus): expose configuring grpc max receive size

- Makefile
- plugins/extractors/bigquery/bigquery.go
Fixes: https://github.com/odpf/compass/issues/153
> fix(bigquery): sanitize unicode null sequence

- metrics/statsd.go
- metrics/statsd_test.go
> feat: send record count as gauge metric

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/plugin_test.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .goreleaser.yml
- README.md
- docs/docs/guides/0_installation.md
> fix: broken build worflow

- agent/retrier.go
If 0 retry is specified via configuration file, do not override it with
default of 5. Only if the configuration is skipped, default to 5.
Example 1 - meteor.yml:
LOG_LEVEL: info
MAX_RETRIES: 5
retries = 5.
Example 2 - meteor.yml:
LOG_LEVEL: info
MAX_RETRIES: 0
retries = 0.
Example 3 - meteor.yml:
LOG_LEVEL: info
retries = 5.
> feat: allow disabling sink retries

- agent/agent.go
- Change log level from INFO to WARN.
- Use human readable formatting for retry delay in log.
Before:
retrying sink in 505050000000
After:
retrying sink in 8m25.05s
Closes #393
> fix: improve log statement for retry sink

- cmd/gen.go
- cmd/info.go
- cmd/lint.go
- cmd/list.go
- cmd/new.go
- cmd/root.go
- cmd/run.go
- config/config.go
- main.go
- test/e2e/e2e_test.go
- Load config only for 'lint' and 'run' commands. This would ensure that
there are no warnings logs related to config file not being found for
commands that do not require it.
- In case the config file is not present, print the error but proceed
with defaults.
- Remove metrics/instrumentation for lint command since it does not
provide any value.
Closes #394
> fix: skip config load for cmds that don't require it

- cmd/lint.go
Before
```
$ meteor lint recipe.yaml
recipe error: urn scope is required to generate unique urnsample: invalid http sink config: Key: 'Config.method' Error:Field validation for 'method' failed on the 'required' tag
sample: invalid labels processor config: Key: 'Config.labels' Error:Field validation for 'labels' failed on the 'required' tag
Some checks were not successful
1 failing, 0 successful, and 1 total
✘  sample	(3 errors, 0 warnings)
```
After
```
$ meteor lint recipe.yaml
recipe error: urn scope is required to generate unique urn
sample: invalid http sink config: Key: 'Config.method' Error:Field validation for 'method' failed on the 'required' tag
Some checks were not successful
1 failing, 0 successful, and 1 total
✘  sample	(2 errors, 0 warnings)
```
> fix(lint): format error message with appropriate line breaks

- cmd/new.go
- generator/recipe.go
- generator/recipe.yaml
Add new mandatory flag --scope to 'meteor new recipe' command for
creating a sample recipe and use the provided scope for generating the
recipe.
BREAKING CHANGE: Method signature for generator.Recipe() changed.
Closes #402.
> fix: accept and use scope for generating recipe

- generator/recipe.go
- generator/recipe.yaml
- plugins/extractors/clickhouse/clickhouse.go
- plugins/extractors/csv/csv.go
- plugins/extractors/elastic/elastic.go
- plugins/extractors/kafka/kafka.go
- plugins/extractors/metabase/metabase.go
- plugins/extractors/mongodb/mongodb.go
- plugins/extractors/mssql/mssql.go
- plugins/extractors/mysql/mysql.go
- plugins/extractors/optimus/optimus.go
- plugins/extractors/oracle/oracle.go
- plugins/extractors/shield/shield.go
- plugins/extractors/tableau/tableau.go
- plugins/processors/enrich/processor.go
- plugins/processors/labels/labels.go
- plugins/sinks/compass/sink.go
- plugins/sinks/file/file.go
- plugins/sinks/http/http.go
- plugins/sinks/kafka/sink.go
- plugins/sinks/stencil/stencil.go
- Introduce and use template helper function on sample configs of
sinks, extractors and processors to replace tabs, if present, with
spaces in sample configs. If tabs are present, parsing the file as
YAML fails.
- Fix sample configs for sinks/http, extractors/{kafka, tableau}.
- Reformat sample configs for consistency.
> fix(gen): format, fix sample configs used for generating recipes

- docs/docs/concepts/recipe.md
- docs/docs/concepts/sink.md
- docs/docs/concepts/source.md
- docs/docs/example/README.md
- docs/docs/guides/0_installation.md
- docs/docs/reference/extractors.md
- yarn build was broken because it could not resolve relative links to README(s) outside the docs folder in extractor's documentation.
- Link to GitHub README files directly to fix broken `yarn build` for docs. Also fix some broken links in docs/docs/example/README.md that _wasn't_ breaking the build.
- Small fixes for recipe, sink, and table formatting.
> fix: don't use relative paths for links outside docs fldr

- .github/workflows/build.yml
- .github/workflows/build_dev.yml
- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/plugin_test.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- plugins/extractors/redash/redash.go
- plugins/extractors/superset/superset.go
- plugins/extractors/superset/superset_test.go
- plugins/extractors/tableau/client.go
- plugins/extractors/tableau/client_test.go
- plugins/sinks/compass/sink.go
- plugins/sinks/compass/sink_test.go
- plugins/sinks/http/http.go
- plugins/sinks/stencil/stencil.go
- plugins/sinks/stencil/stencil_test.go
- recipe/generator_test.go
- test/utils/logger.go
- Bump Go version {1.17 => 1.18}.
- Ensure to fetch the latest version in 'build' and 'release'
workflows to pull in the most up-to-date release so that security
fixes can be included.
- Bump the golangci-lint version {v1.42.1 => v1.50}. This is required
to be able to lint source code with Go 1.18. Fails with 'undeclared
name' errors otherwise.
- Do not run 'go mod tidy' as this can modify the mod file. Changes to
dependencies should be explicitly committed where required.
- Modify release workflow as per
https://goreleaser.com/ci/actions/#workflow.
- Bump action versions:
- actions/setup-go@{v2 => v3}. Enable the 'cache' option for caching
dependency files and build outputs.
- actions/checkout@{v2 => v3}.
- golangci/golangci-lint-action@{v2 => v3}. Caching is enabled by
default. Bump …
> ci: enable cache to speed up jobs

- plugins/extractors/caramlstore/asset_builder.go
- plugins/extractors/caramlstore/testdata/expected-assets.json
Since feature table names are not guarenteed to be unique across projects, including the project name in the URN ensures that they do not conflict.
> fix: include project in URN for caramlstore extractor

- generator/recipe.yaml
- plugins/base_extractor.go
- plugins/extractors/bigquery/bigquery.go
- plugins/extractors/bigtable/bigtable.go
- plugins/extractors/gcs/gcs.go
- plugins/extractors/redshift/redshift.go
User-specified scope is not used in some extractors for generating the URN. Skip validation on the 'scope' being present for such cases:
- bigquery
- bigtable
- gcs
- redshift
> fix: skip validation for recipe scope if unneeded

- plugins/extractors/application_yaml/README.md
- plugins/extractors/bigquery/README.md
- plugins/extractors/caramlstore/README.md
- application_yaml extractor:
- Fix usage for - format for 'input' and 'output' fields.
- Drop fields `lineage.{upstreams, downstreams}[].{type, service}` from outputs section.
- In the bigquery extractor, replace reference to 'credentials_json' with 'service_account_json' and 'service_account_base64'.
- In the caramlstore extractor, fix the value format and sample for 'resource.urn' in outputs section.
> docs: fix minor issues

- cmd/lint.go
- cmd/run.go
- plugins/base_plugin_test.go
- plugins/errors.go
- plugins/errors_test.go
- plugins/util.go
- Include plugin name in the error message when it is not found.
- Include the validation failure message along with the line number in
the error message for plugin config.
- During lint, include the recipe name while printing errors that are 
neither 'not found' nor 'invalid config' errors.
- During run, on run failure, include recipe name in the error log 
context.
- Include details of the validation failures in the error message for
InvalidConfigError. This gets printed while trying to run the recipe.
BEFORE:
$ meteor run run ./_recipes/caramlstore-stg-wth-script-invalid.yaml
INFO[0000] running recipe                                recipe=caramlstore-stg-wth-script-invalid
ERRO[0000] error running recipe                          duration_ms=189 err="failed to setup processor: could not …
> fix: improve error messages

- plugins/extractors/bigquery/README.md
- plugins/extractors/bigquery/bigquery.go
- plugins/extractors/bigquery/bigquery_test.go
* add exclusion filters to bigquery recipe to able to exclude a list of datasets or tables
Closes #436
> feat(bigquery): add exclusion filters for datasets and tables

- agent/agent_test.go
- agent/stream.go
With multiple processors, the changes by the a given processor would be lost when the next processor was run. Use the result from running the processor while calling the next one.
Closes #444
> fix: carry forward changes by prev processor for next

- utils/custom_properties.go
- utils/custom_properties_test.go
Type specific handling has a good chance of becoming outdated if and when new attribute types are introduced. Address with following:
- Use type assertion on generic proto message to check for the presence of attributes field for retrieving as map.
- Use Go reflection to find the field by name and set value to new attributes created using given map.
> refactor: use generic handling for getting/setting attributes

- agent/agent.go
- agent/stream.go
- plugins/extractors/merlin/merlin.go
- Use atomic int for incrementing record count in agent run.
- Protect fields that can be concurrently modified in a stream instance using a mutex.
- Don't modify slice to collect runs concurrently while running multiple recipes in agent. Use channels to collect runs instead.
- Avoid referring to and modification of errors or values declared outside closures.
> fix: avoid race conditions from concurrent modification of data

- Makefile
- plugins/extractors/application_yaml/README.md
- plugins/extractors/caramlstore/README.md
- plugins/extractors/caramlstore/asset_builder.go
- plugins/extractors/caramlstore/testdata/expected-assets.json
- plugins/extractors/merlin/README.md
- plugins/processors/script/README.md
- Populate fields 'Description' and 'Type' for FeatureTable_Entity while extracting assets from CaraML Store.
- Bump proton commit to include changes "feat: add attributes field for v1beta2 asset types (#233)".
Related to changes made in https://github.com/odpf/proton/pull/224.
> feat: populate new fields of Entity in caramlstore extractor

- agent/agent.go
- agent/agent_test.go
- agent/stream.go
- plugins/sinks/file/file.go
- plugins/sinks/file/file_test.go
- Split stream.Close() into Shutdown() and Close(). Shutdown() is
expected to be called once all the records are extracted and Close()
is expected to be called once all records are written by sinks. If
Close() is called first, it will call Shutdown() internally.
- Close the File instance in file sink's Close() method. Minor
refactoring to improve perf for ndjson output (avoid string concat).
(builds on #446 to avoid conflicts)
Closes #380.
> fix: close sinks after records are written

- recipe/envs.go
- recipe/reader_test.go
- recipe/sample_config.yaml
- recipe/testdata/config2.yaml
> fix: load env vars having $ in value correctly

- docs/docs/reference/extractors.md
- plugins/base_plugin_test.go
- plugins/extractors/application_yaml/README.md
- plugins/extractors/application_yaml/application_yaml.go
- plugins/extractors/caramlstore/README.md
- plugins/extractors/http/README.md
- plugins/extractors/http/execute_request.go
- plugins/extractors/http/execute_script.go
- plugins/extractors/http/execute_script_test.go
- plugins/extractors/http/http_extractor.go
- plugins/extractors/http/http_extractor_test.go
- plugins/extractors/populate.go
- plugins/internal/tengoutil/secure_script.go
- plugins/internal/tengoutil/secure_script_test.go
- plugins/processors/script/README.md
- plugins/util.go
- test/utils/assert.go
- Add HTTP extractor, a generic extractor that uses a script capable of
emitting any type of asset.
- Fix config error field key to support nested fields.
- Disallow import of os module from scripts.
- Remove unnecessary init method on application extractor.
- Add test helper to assert slice of protos.
Depends on #434, that needs to be merged first. 
Closes #413
> feat: add HTTP extractor

- plugins/extractors/http/README.md
- plugins/extractors/http/execute_request.go
- plugins/extractors/http/execute_script.go
- plugins/extractors/http/http_extractor.go
- plugins/extractors/http/http_extractor_test.go
- plugins/internal/tengoutil/secure_script.go
- plugins/internal/tengoutil/secure_script_test.go
- plugins/internal/tengoutil/structmap/structmap.go
- plugins/internal/tengoutil/structmap/structmap_test.go
- plugins/processors/script/tengo_script.go
- Add script global function `execute_request` for being able to execute 1 or more HTTP requests using the request configuration options similar to recipe config.
- Instead of only providing the response body to the script, provide the {status_code, header, body}.
- Allow configuration of concurrency to control the number of concurrent HTTP requests made from inside the script.
BREAKING CHANGE: The response provided to the script in HTTP extractor has the {status_code, header, body} instead of just the response body.
> feat!: extend HTTP extractor

- cmd/new.go
- generator/recipe.go
Meteor `new` command allows user to generate recipe, although the functionality is fine, I want use this method to generate recipe outside of meteor as well. If this is being called programmatically printing it to hard coded stdout blocked me to take the output as a string.
> fix: extract io writer in recipe generator

- plugins/extractors/http/README.md
- plugins/extractors/http/execute_script.go
- plugins/extractors/http/http_extractor.go
- plugins/extractors/http/http_extractor_test.go
- Allow configuration of the max_allocs and max_const_objects that limit memory allocation in the script env.
- Pass the recipe's scope as a script global so that it can be used to construct the asset's URN if needed.
> feat: enhance HTTP extractor's script options

- plugins/sinks/compass/sink.go
- plugins/sinks/compass/sink_test.go
Labels were not being sent to Compass if no labels were specified in the sink configuration for Compass.
> fix: Sink asset labels to Compass

- plugins/extractors/cassandra/README.md
- plugins/extractors/cassandra/cassandra.go
- plugins/extractors/clickhouse/README.md
- plugins/extractors/clickhouse/clickhouse.go
- plugins/extractors/couchdb/README.md
- plugins/extractors/couchdb/couchdb.go
- plugins/extractors/gcs/README.md
- plugins/extractors/gcs/gcs.go
- plugins/extractors/grafana/README.md
- plugins/extractors/grafana/grafana.go
- plugins/extractors/mariadb/README.md
- plugins/extractors/mariadb/mariadb.go
- plugins/extractors/mongodb/README.md
- plugins/extractors/mongodb/mongodb.go
- plugins/extractors/mssql/README.md
- plugins/extractors/mssql/mssql.go
- plugins/extractors/mysql/README.md
- plugins/extractors/mysql/mysql.go
- plugins/extractors/snowflake/README.md
- plugins/extractors/snowflake/snowflake.go
Adding option to exclude resources from being crawled from extractors
**Note**: Metabase and Snowflake API responses have changed and the meteor extractors needs to be edited to support different versions
> feat(extractor-plugins): add crawler specifications
